comment out only test

diff --git a/.github/actions/e2e-with-docker/action.yml b/.github/actions/e2e-with-docker/action.yml
--- a/.github/actions/e2e-with-docker/action.yml
+++ b/.github/actions/e2e-with-docker/action.yml
@@ -43,19 +43,19 @@ runs:
         docker exec -d ${{ steps.extract_container_id.outputs.container_id }} /tmp/nodex-agent
         sleep 3
     
-    - name: (run) show docker ps
-      shell: bash
-      run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e ps
+    # - name: (run) show docker ps
+    #   shell: bash
+    #   run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e ps
 
-    - name: (run) only one process test
-      shell: bash
-      run: |
-        processes=$(docker exec ${{ steps.extract_container_id.outputs.container_id }} pgrep -f nodex-agent)
-        process_count=$(echo "$processes" | wc -l)
-        if [ "$process_count" -ne 1 ]; then
-            echo "Error: Expected 1 nodex-agent process, but found $process_count."
-            exit 1
-        fi
+    # - name: (run) only one process test
+    #   shell: bash
+    #   run: |
+    #     processes=$(docker exec ${{ steps.extract_container_id.outputs.container_id }} pgrep -f nodex-agent)
+    #     process_count=$(echo "$processes" | wc -l)
+    #     if [ "$process_count" -ne 1 ]; then
+    #         echo "Error: Expected 1 nodex-agent process, but found $process_count."
+    #         exit 1
+    #     fi
 
     - name: (run) shutdown agent by SIGINT
       shell: bash
