add test

diff --git a/.github/actions/e2e/action.yml b/.github/actions/e2e/action.yml
--- a/.github/actions/e2e/action.yml
+++ b/.github/actions/e2e/action.yml
@@ -57,6 +57,25 @@ runs:
       working-directory: e2e
       run: cargo test
 
+    - name: (run) only one process test
+      uses: nick-fields/retry@v3
+      with:
+        timeout_seconds: 120
+        max_attempts: 10
+        retry_on: error
+        # This command failed many times on MacOS runners, so it was automatically retried.
+        command: |
+          ${{ inputs.binary-path }} > log.txt 2>&1 &
+          sleep 3
+          if [ "$(pgrep -x nodex-agent | wc -l)" -ne 1 ]; then
+            exit 1
+          fi
+      env:
+        NODEX_DID_HTTP_ENDPOINT: http://localhost:4010
+        NODEX_DID_ATTACHMENT_LINK: http://localhost:4010
+        NODEX_HUB_HTTP_ENDPOINT: http://localhost:8020
+        RUST_BACKTRACE: 1
+
     - name: (run) shutdown agent by SIGINT
       shell: bash
       run: |
