add shutdown test on e2e

diff --git a/.github/actions/e2e/action.yml b/.github/actions/e2e/action.yml
--- a/.github/actions/e2e/action.yml
+++ b/.github/actions/e2e/action.yml
@@ -66,3 +66,33 @@ runs:
       shell: bash
       run: docker compose -f test_resource/compose.yaml logs
       if: ${{ always() }}
+
+    - name: (run) shutdown agent
+      shell: bash
+      run: |
+        container_id=$(docker compose -f test_resource/compose.yaml ps -q e2e_agent)
+        pid=$(docker exec $container_id pgrep -f nodex-agent)
+        docker exec $container_id kill -SIGINT $pid
+      if: ${{ always() }}
+
+    - name: (run) Check for 'stopped' log message
+      shell: bash
+      id: check_logs
+      run: |
+        if docker compose -f test_resource/compose.yaml logs e2e_agent | grep -q "stopped"; then
+          echo "::set-output name=stopped_found::true"
+        else
+          echo "::set-output name=stopped_found::false"
+        fi
+
+    - name: (run)  Verify process is not running in e2e_agent
+      shell: bash
+      if: steps.check_logs.outputs.stopped_found == 'true'
+      run: |
+        container_id=$(docker compose -f test_resource/compose.yaml ps -q e2e_agent)
+        if ! docker exec $container_id pgrep -f /tmp/nodex-agent; then
+          echo "Process not found, as expected."
+        else
+          echo "Process is still running, which is not expected."
+          exit 1
+        fi
